### ISSUE TITLE
Great Guardian Missing Permanently

### ISSUE THREAD

**Issue by MiningGuild** [horse4lunch/Great-Guardian-Hider#4]
The guardian does not appear when I have guardian stones in the inventory. I uninstalled the plugin and the guardian is still missing. 

I made sure the plugin had been removed from the plugins folder. Still gone. Cleared cache, reinstalled Runelite, still gone.

Runelite for Intel Mac

**Comment by horse4lunch** [comment]
I didn't have membership to mess with this at the time, But I just started playing again and its working for me. You might of had a conflicting plugin. It could be something completely unrelated or more likely someone has added similar functionality to hide the guardian in a rune crafting plugin.
